name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Setup Python on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.11"
      run: ./configure

    - name: Install dependencies
      run: make install

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
